---
# This playbook makes a hypervisor

- name: apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common

  handlers: 
    - name: restart sshd
      service:
        name: sshd
        state: restarted
