---

- name: Install cockpit for monitoring
  yum: name={{ item }} state=present
  with_items:
   - cockpit
   - cockpit-pcp
   - tuned

- name: start cockpit
  service: 
    name: cockpit
    state: started
    enabled: yes

- name: start tuned
  service: 
    name: tuned
    state: started
    enabled: yes
