---

- name: "Install preferred packages"
  yum: name={{ item }} state=present
  with_items:
   - vim 
   - wget 
   - git 
   - bind-utils 

- name: "Nice to have extra packages"
  yum: name={{ item }} state=present
  with_items:
   - emacs-nox 
   - redhat-lsb
